Diff aggregation
kalkih/mini-graph-card pull request #601
Opened 2021-05-06 19:37 UTC by mhspelt

2021-05-24 12:21 UTC, OmgImAlexis commented
@mhspelt please rebase.

2021-05-25 06:54 UTC, mhspelt commented
I thought that was what I did with #601. As a Mercurial user I'm still a
bit confused by git's idea of branches, can you help me out a bit please?

On Mon, 24 May 2021 at 14:21, Alexis Tyler ***@***.***> wrote:

> @mhspelt <https://github.com/mhspelt> please rebase.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kalkih/mini-graph-card/pull/601#issuecomment-847005672>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFBX4IPJIVB42JWHNVOWQXDTPJAGJANCNFSM44HYHDFQ>
> .
>

2021-09-24 16:33 UTC, kalkih commented
Please add documentation for this: https://github.com/kalkih/mini-graph-card/tree/dev#aggregate-functions

2022-01-15 12:45 UTC, jlsjonas commented
@mhspelt Could you please add documentation for this feature as requested?
Thanks for your contribution! (we'll take care of rebasing during merge, as we understand you're unfamiliar with the process)

2022-01-15 12:45 UTC, jlsjonas requested changes
Could you please add documentation for this feature?

2022-01-17 18:29 UTC, mhspelt commented
Hi @jlsjonas, I've added and pushed to https://github.com/mhspelt/mini-graph-card
I don't really see the commit in this PR yet, does it synchronize automatically?

2022-01-17 21:26 UTC, jlsjonas commented on src/graph.js
> +    if (this.aggregateFuncName === 'delta' || this.aggregateFuncName === 'diff') {
```suggestion
    if (['delta', 'diff'].includes(this.aggregateFuncName)) {
```
For improved readability I'd suggest this small change, thanks for the contribution!

2022-01-17 21:30 UTC, jlsjonas approved these changes

2022-01-17 22:30 UTC, merged