feat: add value_multiplier and extend value_factor
kalkih/mini-graph-card pull request #608
Opened 2021-05-24 12:20 UTC by OmgImAlexis

This adds value_multiplier which similarly to the value_factor only it multiplies the value directly. By default it's set to `1`.

I've also added the `value_factor` to the entity itself to allow different factors for each entity. Personally I like this as it allows cards to show more than a single type of data. For example I want to show data usage and power usage on one, the issue is one is in bytes(I want MB) and one is watts(I want KW). I need one to be divided by `1024` and the other `1000`.

Closes https://github.com/kalkih/mini-graph-card/issues/607 and https://github.com/kalkih/mini-graph-card/issues/591

2021-08-10 11:29 UTC, maulwuff commented
Is there anything missing to complete this PR? 
I'd like to compare sun elevation with solar power and I need to scale the evelation up to make it visible :)

2021-08-10 23:27 UTC, OmgImAlexis commented
@maulwuff I don't think so.

2021-09-24 16:28 UTC, kalkih commented
> Is there anything missing to complete this PR?
> I'd like to compare sun elevation with solar power and I need to scale the evelation up to make it visible :)

The review comments need to be addressed before we can merge this.

2021-09-25 00:46 UTC, OmgImAlexis commented
> The review comments need to be addressed before we can merge this.

There are no review comments..?

2021-09-25 07:36 UTC, kalkih requested changes

2021-10-08 18:35 UTC, maulwuff commented
@OmgImAlexis come on, you can fix that ;-)

2021-11-15 17:30 UTC, smiba commented
Would love to see this in mini-graph-card, currently this prohibits me from making a total power draw card. My total consumption is reported in kW, while individual devices report in W.

2021-11-15 19:08 UTC, kalkih commented
> Would love to see this in mini-graph-card, currently this prohibits me from making a total power draw card. My total consumption is reported in kW, while individual devices report in W.

In the meantime you could look at creating a template_sensor and handle the conversion there.

2022-01-02 14:31 UTC, jlsjonas commented
@OmgImAlexis Do you need some help addressing these (minor) comments & getting this merged?

2022-02-11 17:23 UTC, ildar170975 commented
Please check this: https://github.com/kalkih/mini-graph-card/issues/591#issuecomment-1036431648
As far as I understood, this PR introduces a new `value_multiplier` property in addition to the already present (but not per-entity) `value_factor` property.
IMHO there should be ONE multiplying property.

2022-05-18 09:58 UTC, andrewjswan commented
Great idea, then I can invert the graph to get this result:
![image](https://user-images.githubusercontent.com/3609660/169013016-e9c2920e-f77b-4ed8-b312-2bc0200496d2.png)

2026-06-26 02:27 UTC, ildar170975 commented
No feedback from the author for a long time...
Closed in favour of https://github.com/kalkih/mini-graph-card/pull/1359 which supports both "exponent" factor & proposed here "multiplier" factor.

2026-06-26 02:27 UTC, closed without merging

2026-08-28 11:09 UTC, andrewjswan commented
> Closed in favour of #1359 which supports both "exponent" factor & proposed here "multiplier" factor.

But it still doesn't allow you to invert the graph as shown in the example https://github.com/kalkih/mini-graph-card/pull/608#issuecomment-1129812319

2026-08-28 13:12 UTC, ildar170975 commented
> But it still doesn't allow you to invert the graph

1. Although this PR proposed an individual per-entity factor, it was incomplete. Adding that per-entity factor will be a next improvement after https://github.com/kalkih/mini-graph-card/pull/1359, it is planned.
2. A negative factor is not a sufficient way to invert a graph since it will give negative value/labels/extremas. A corresponding "invert /mirror graph" feature is planned.

2026-08-29 14:50 UTC, andrewjswan commented
> 2\. A negative factor is not a sufficient way to invert a graph since it will give negative value/labels/extremas.

In my opinion, this doesn't matter, but it does highlight a problem with the architecture—in theory, all data coefficients should affect only the graph, not the values. But overall, any solution will work.

2026-08-29 16:59 UTC, ildar170975 commented
@andrewjswan 
The `invert` option is one of the 1st priority.
Надо чуть подождать))

Meanwhile, to display an "inverted" graph you can use card-mod - https://community.home-assistant.io/t/lovelace-mini-graph-card/71385/1936?u=ildar_gabdullin

<img width="490" height="372" alt="image" src="https://github.com/user-attachments/assets/b1721d1c-65ea-4922-a84a-3450f74bdcc2" />

More card-mod styles here -  https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/1396

2026-09-01 05:07 UTC, ildar170975 commented
Proof of concept for an inverted graph, coming soon:

<img width="960" height="634" alt="image" src="https://github.com/user-attachments/assets/4aa048b2-a77d-4a47-9f7f-5d4401c7bc31" />

2026-09-01 05:22 UTC, andrewjswan commented
> Proof of concept for an inverted graph, coming soon:

In my opinion, inverting along the second axis is the worst option. If you look at the traffic graph, In/Out is on one axis, Out is inverted, and the second axis can contain other data.

2026-09-01 05:24 UTC, andrewjswan commented
<img width="1220" height="954" alt="Screenshot_2026-09-01-08-23-30-767_io homeassistant companion android-edit" src="https://github.com/user-attachments/assets/4fa75359-bced-42a7-a3d5-827982468706" />

2026-09-01 05:30 UTC, ildar170975 commented
As was already told, ypu cannot invert a graph w/o inverting a scale; applying a negative factor is a bad way since it will show negative values.
As for "secondary axis is used for other needs" - come on, you need it for a background graph like "day/night", "on/off" - and all these binary-based graphs will be a separate functionality with VERTICAL transitions (will not need a dedicated axis).

2026-09-01 05:42 UTC, andrewjswan commented
I don't see any problems. Here's a chart that provides a great understanding of the scale and trends in traffic. It uses two axes: the first shows traffic, and the second shows additional data. If you were to invert the axes, you'd need to add at least one more axis.

<img width="1220" height="802" alt="Screenshot_2026-09-01-08-36-24-626_io homeassistant companion android-edit" src="https://github.com/user-attachments/assets/817d9a84-fc46-4f9d-a367-3fb18b7b0584" />




> As for "secondary axis is used for other needs" - come on, you need it for a background graph like "day/night", "on/off" - and all these binary-based graphs

Not just the amount of free storage space, remaining data allowance under your plan, and so on.

> since it will show negative values.

Oh, come on—there aren't any negative values on the graph above, and everything is perfectly clear.

2026-09-01 05:49 UTC, ildar170975 commented
Assume you applied a negative factor to a graph.
Then you will see a nice line - but wrong states if you switch them on (and a negative Y scale if you switch labels on).
(not to mention possible future extrema/avg data lines supported for other entities)
The fact that you do not see negative states does not mean they are not.
Means - applying a negative factor is a mere hack which leads to an inconsistency.

Factor (exponential, scale) - are only supposed to be used when you do not want to create template sensors with a required conversion; using a negative -1 factor only to see an inverted graph is a hack which hopefully will be not needed in future.

2026-09-01 09:25 UTC, andrewjswan commented
> The fact that you do not see negative states does not mean they are not.
> Means - applying a negative factor is a mere hack which leads to an inconsistency.

Inconsistent with what? Let’s say there are two metrics on the graph—Download and Upload. I apply a factor of -1 to Upload and get an inverted graph. Even if I see -20 Mb there, I fully understand that I sent 20 Mb. And there are no inconsistencies. And everything is perfectly clear, both in terms of the values and the axes. If I don’t need this behavior, I simply don’t apply the -1 multiplier and can use your inversion method instead—but then I lose the functionality of the second axis.
Everyone will choose the approach that works best for them. That’s the beauty of customization.

> Factor (exponential, scale) - are only supposed to be used when you do not want to create template sensors with a required conversion; using a negative -1 factor only to see an inverted graph is a hack which hopefully will be not needed in future.

Well, since we're expanding the customization options, why should we restrict people in any way? If someone sets the coefficient to -1, they understand the consequences and are comfortable with them.

2026-09-01 23:59 UTC, ildar170975 commented
The inconsistency comes when you show a state of the “minused” entity - it will show a negative state. Repeat, your “-1” method is a hack with a limited application “do not switch on showing a state, do not switch on showing axis labels”.
As long as you agree to use this hack - you are welcome, but we should provide/use consistent methods. 
Also, I agree that the secondary axis becomes occupied in case of the “my” method. Thinking about a tertiary axis without showing axis labels.

2026-09-02 04:33 UTC, andrewjswan commented
Inversion around 0 is simply the transformation of 5 to -5. It doesn’t matter how it’s done—whether by a flag or a coefficient. And since the user has chosen inversion, they understand that the values on the axes may change. I don’t see any problem with displaying values and axes that will have negative values for the inverted graph, since anything less than 0 is negative.