State history
kalkih/mini-graph-card pull request #693
Opened 2022-01-17 03:31 UTC by wallbasher

Prepping work for having state history graph shown above/below existing graphs, these have full color state mapping specification.

Adds options to show hour bars every x hours

![image](https://user-images.githubusercontent.com/1956918/149703818-39cd679f-b52b-40ca-9dbe-4371f478fa96.png)
![image](https://user-images.githubusercontent.com/1956918/149703856-eef2eec4-8f17-47c7-b8de-5bd8d4c80fc7.png)
![image](https://user-images.githubusercontent.com/1956918/149703887-ed6aeeba-08d1-42b9-a968-391683f2ac6d.png)

2022-01-17 04:02 UTC, wallbasher commented on src/style.js
> +    padding: 0px;
Make this a value that can be set, for some reason when I set this here to another value the history bars on top would not show up.  This is the only "impact" on the original library.

2022-02-08 11:03 UTC, jlsjonas requested changes
Hi, thanks for your contribution!
I'm not entirely convinced on the added complexity & duplicated code to accomplish this though, but I'm not against the concept of adding it.

We plan on reworking the configuration & general codebase to make it more structured, it might benefit to wait for that release to implement this feature in a more sustainable way.

(only partially reviewed, for this reason; apologies for it getting stuck in pending for a while)

2022-02-17 04:36 UTC, wallbasher commented on src/main.js
> +          <div class="states--secondary">${this.normalEntities().map((ent, i) => this.renderState(ent, i))}</div>
Sorry about that must have missed it, I started this a year ago then finally got around to finishing it.

2022-02-17 04:39 UTC, wallbasher commented
I really like the mini-graph, but if falls short in having States displayed.  I wanted something that could get close to what exists in the ecobee system.  

Image examples:
https://www.reddit.com/r/ecobee/comments/gh6kli/help_me_understand_the_system_usage_graph/

2022-04-03 03:16 UTC, closed without merging